# Generated by Django 3.1.6 on 2021-03-08 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_auto_20210307_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='contenido',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Contenido'),
            preserve_default=False,
        ),
    ]
